---
- name: Install Ghosts Server
  hosts: ghost_server
  remote_user: root

  tasks:
  - name: Install ansible and galaxy
    apt:
      pkg:
      - ansible
      - ansible-galaxy
      state: latest
    when: "'ansible-host' in inventory_hostname"

  - name: Install docker
    apt:
     pkg:
       - docker
       - docker-compose
       state: latest
      when: "'ghostserver' in inventory_hostname"



  -name: Download GHOSTS server binary files
   get_url:
     url: https://raw.githubusercontent.com/cmu-sei/GHOSTS/master/src/Ghosts.Api/docker-compose.yml
     dest: /tmp/docker-compose.yml
    when: "'ghostserver' in inventory_hostname"

  -name: Create and start d ocker services for GHOST server
   community.docker.docker_compose:
     project_src: /tmp
   register: output
   when: "'ghostserver' in inventory_hostname"
